services:
  - type: web
    name: plushie-panic
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /api/estado
    autoDeployTrigger: off