name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar frontend
        run: npm install --prefix frontend

      - name: Instalar backend
        run: npm install --prefix backend

      - name: Ejecutar linters
        run: npm run lint